average method
sepandhaghighi/pycm pull request #333
Opened 2020-09-04 11:46 UTC by sadrasabouri

#### Reference Issues/PRs
#332 
#### What does this implement/fix? Explain your changes.
+ `average` method simplified by use of `weighted_average`

some tests have been changed due to probable precision differences.

2020-09-04 22:03 UTC, sepandhaghighi requested changes

2020-09-04 22:03 UTC, sepandhaghighi commented on CHANGELOG.md
> +### Changed
@sadrasabouri Please move `#Changed` after `#Added`

2020-09-04 22:04 UTC, sepandhaghighi commented
@alirezazolanvari Please review this PR.

2020-09-04 22:31 UTC, sepandhaghighi commented on CHANGELOG.md
> +### Changed
After this minor edit I will approve this PR 💯

2020-09-07 12:42 UTC, alirezazolanvari approved these changes

2020-09-08 09:56 UTC, sepandhaghighi approved these changes

2020-09-08 09:56 UTC, merged