Copy method
sepandhaghighi/pycm pull request #334
Opened 2020-09-08 12:25 UTC by sadrasabouri

#### Reference Issues/PRs
#327 
#### What does this implement/fix? Explain your changes.
In this pull request I've added:

+ `__copy__` method for making copy of confusion matrix object when using `cm_ = copy.copy(cm)`
+ `copy` method for doing that by `cm_ = cm.copy()` 

There are some tests showing identity and seperation of these copies which means any copy of matrix should be identically the same using `cm_ == cm` (which should logically be true) and stored in different positions in memory using `id(cm_) == id(cm)` (which should be logically false).

2020-09-08 12:35 UTC, sepandhaghighi requested changes

2020-09-08 12:35 UTC, sepandhaghighi commented on pycm/pycm_obj.py
> +    def __copy__(self):
Add docstring for this method

2020-09-08 12:35 UTC, sepandhaghighi commented on pycm/pycm_obj.py
> +    def copy(self):
Add docstring for this method

2020-09-08 21:55 UTC, sepandhaghighi approved these changes

2020-09-08 21:56 UTC, sepandhaghighi commented
@alirezazolanvari 
Please review this PR.
If everything is okay merge it after approval

2020-09-09 11:12 UTC, alirezazolanvari approved these changes

2020-09-09 11:12 UTC, merged