Combine method
sepandhaghighi/pycm pull request #340
Opened 2020-09-25 08:38 UTC by sadrasabouri

#### Reference Issues/PRs
#326 
#### What does this implement/fix? Explain your changes.
In this PR `combine` method added.
We have 2 approaches for implementing this method:
+ [Intersection](https://github.com/sepandhaghighi/pycm/commit/3e2d3009f4981c071eff32e0610492adb5ed8b09)
In this approach new matrix will be calculated from intersection of two combining matrix classes.
for example we have:
```
>>> cm1 = ConfusionMatrix([1,2,3,1],[1,3,2,2])
>>> cm1.matrix
{1: {1: 1, 2: 1, 3: 0}, 2: {1: 0, 2: 0, 3: 1}, 3: {1: 0, 2: 1, 3: 0}}
>>> cm2 = ConfusionMatrix([4,2,2,1],[1,1,2,4])
>>> cm2.matrix
{1: {1: 0, 2: 0, 4: 1}, 2: {1: 1, 2: 1, 4: 0}, 4: {1: 1, 2: 0, 4: 0}}
>>> cm_combined = cm1.combine(cm2)
>>> cm_combined.matrix
{1: {1: 1, 2: 1}, 2: {1: 1, 2: 1}}
```
+ [Union](https://github.com/sepandhaghighi/pycm/commit/18958ab505e7a09d9e1a626f9bb0b472b4e1e90e)
In this approach new matrix will be calculated from intersection of two combining matrix classes.
for example we have:
```
>>> cm1 = ConfusionMatrix([1,2,3,1],[1,3,2,2])
>>> cm1.matrix
{1: {1: 1, 2: 1, 3: 0}, 2: {1: 0, 2: 0, 3: 1}, 3: {1: 0, 2: 1, 3: 0}}
>>> cm2 = ConfusionMatrix([4,2,2,1],[1,1,2,4])
>>> cm2.matrix
{1: {1: 0, 2: 0, 4: 1}, 2: {1: 1, 2: 1, 4: 0}, 4: {1: 1, 2: 0, 4: 0}}
>>> cm_combined = cm1.combine(cm2)
>>> cm_combined.matrix
{1: {1: 1, 2: 1, 3: 0, 4: 1}, 2: {1: 1, 2: 1, 3: 1, 4: 0}, 3: {1: 0, 2: 1, 3: 0, 4: 0}, 4: {1: 1, 2: 0, 3: 0, 4: 0}}
```

Anyway tests are now based on second approach.

@sepandhaghighi what we should decide what should we do for bad input (none `ConfusionMatrix` input)?
Should I add new exception for this method?

2020-09-25 08:51 UTC, sadrasabouri commented
I'll add more tests for solving codecov failure, what can I do for codefactor?

2020-09-25 11:44 UTC, sepandhaghighi requested changes

2020-09-25 11:44 UTC, sepandhaghighi commented on CHANGELOG.md
> +- `combine` method
`### Added` missed

2020-09-25 11:44 UTC, sepandhaghighi commented on pycm/pycm_obj.py
> +        result_matrix = {}
Please move this section (`878` to `889`) to a function in `pycm_util.py`.
Call it `matrix_combine`

2020-09-25 11:44 UTC, sepandhaghighi commented on pycm/pycm_obj.py
> +        :return: combine of two matrices as Confusion matrix
as a new Confusion matrix

2020-09-25 11:44 UTC, sepandhaghighi commented on pycm/pycm_obj.py
> +    def combine(self, other):
**For error checking :**
1. Error Type : `pycmMatrixError`
2. Error Message : `The input type is considered to be pycm.ConfusionMatrix object but it's not!`
3. Error Variable Name : `COMBINE_TYPE_ERROR`

2020-09-27 17:58 UTC, sepandhaghighi commented
@sadrasabouri 
Thanks for your effort 💯 
Everything looks good!
I will update the document in next few days and then complete my review.

2020-09-28 16:40 UTC, alirezazolanvari approved these changes

2020-09-28 22:37 UTC, sepandhaghighi approved these changes

2020-09-28 22:41 UTC, merged