Refs unification
sepandhaghighi/pycm pull request #362
Opened 2021-01-25 22:56 UTC by alirezazolanvari

#### Reference Issues/PRs
#173 

#### What does this implement/fix? Explain your changes.
The references are unified with IEEE format

#### Any other comments?
Please carefully compare the new references' titles with the previous ones. Be sure that the formats are correct.

2021-01-27 12:54 UTC, sepandhaghighi commented
@alirezazolanvari Thanks for your efforts 💯 
I will review this PR in the next few days.
But as a side note, I think it would better if we mention `IEEE` format somewhere in `CONTRIBUTING.md`

2021-01-30 08:14 UTC, sadrasabouri requested changes
Thank you @alirezazolanvari :1st_place_medal: 
There were tiny things that I mentioned in comments, also there were some changes in date of each references that I decided not to mention them (due to make the review lighter) but there should be reasonable reason why these changes are necessary.

2021-01-30 08:14 UTC, sadrasabouri commented on README.md
> +<blockquote>35- S. Brin, R. Motwani, J. D. Ullman, and S. Tsur, "Dynamic itemset counting and implication rules for market basket data," in <i>Proceedings of the 1997 ACM SIGMOD international confere
another blank space here :point_up:

2021-01-30 08:14 UTC, sadrasabouri commented on README.md
> +<blockquote>37- J. Bray and J. Curtis, "An ordination of upland forest communities of southern Wisconsin. Ecological Monographs (27)," ed: PRIMER-E Plymouth, 1957, pp. 325-349.</blockquote>
another blank space here :point_up:

2021-01-30 08:14 UTC, sadrasabouri commented on README.md
> +<blockquote>38- J. L. Fleiss, J. Cohen, and B. S. Everitt, "Large sample standard errors of kappa and weighted kappa," <i>Psychological bulletin</i>, vol. 72, no. 5, p. 323, 1969.</blockquote>
another blank space here :point_up:

2021-01-30 08:14 UTC, sadrasabouri commented on README.md
> +<blockquote>40- R. Ranawana and V. Palade, "Optimized precision-a new measure for classifier performance evaluation," in <i>2006 IEEE International Conference on Evolutionary Computation</i>, 2006: I
another white space here :point_up:

2021-01-30 08:16 UTC, sadrasabouri commented
> @alirezazolanvari Thanks for your efforts 100
> I will review this PR in the next few days.
> But as a side note, I think it would better if we mention `IEEE` format somewhere in `CONTRIBUTING.md`

Also logging this change in `CHANGELOG.md` may be helpful.

2021-01-31 09:51 UTC, alirezazolanvari commented on README.md
> +<blockquote>19- R. Delgado and J. D. Núnez-González, "Enhancing confusion entropy as measure for evaluating classifiers," in <i>The 13th International Conference on Soft Computing Models in Industria
In IEEE format for citing conference papers, `in` should be written before the conference's name.

2021-01-31 10:25 UTC, sadrasabouri approved these changes

2021-02-02 15:12 UTC, sepandhaghighi requested changes

2021-02-02 15:12 UTC, sepandhaghighi commented on README.md
> +<blockquote>55- K. Boyd, K. H. Eng, and C. D. Page, "Area under the precision-recall curve: point estimates and confidence intervals," in <i>Joint European conferenceon machine learning and knowledge
`conferenceon`?

2021-02-02 15:12 UTC, sepandhaghighi commented on README.md
> +<blockquote>57- M. Kuhn, "Building predictive models in R using the caret package," <i>J Stat Softw</i>, vol. 28, no. 5, pp. 1-26, 2008.</blockquote>
Journal name is `Journal of statistical software`

https://www.jstatsoft.org/article/view/v028i05

2021-02-02 15:13 UTC, sepandhaghighi commented
@alirezazolanvari 
Please take a look at my comments, then I will update `CHANGELOG.md`, `CONTRIBUTING.md` and `Document.ipynb`

2021-02-10 23:56 UTC, sepandhaghighi approved these changes

2021-02-11 00:13 UTC, sepandhaghighi commented
LGTM 👍 
@sadrasabouri @alirezazolanvari Please take a look at my commits (https://github.com/sepandhaghighi/pycm/pull/362/commits/0bf28f46cec4599659e624c5074e57bd2de5090a, https://github.com/sepandhaghighi/pycm/pull/362/commits/cd416c1f14c8432aeb957b149d0d5be204e80b7c, https://github.com/sepandhaghighi/pycm/pull/362/commits/ad546700702c24906f4e1dee03133bfbaaa2fc00)
If everything is okay, please merge this `PR` after approval.

2021-02-12 12:45 UTC, sadrasabouri approved these changes
LGTM

2021-02-12 17:54 UTC, merged