Use long class names in html output files
sepandhaghighi/pycm pull request #371
Opened 2021-03-27 14:02 UTC by sadrasabouri

#### Reference Issues/PRs
#364 
#### What does this implement/fix? Explain your changes.
new boolean parameter named `use_long_names` added to `save_html` function which provides us to use long class names in html output files

2021-03-27 21:03 UTC, sepandhaghighi requested changes
@sadrasabouri Thanks for your effort 💯 
I suggest `shortener` (default : `True`) instead of `use_long_names`, whats your idea?

2021-03-28 12:50 UTC, sepandhaghighi requested changes

2021-03-28 12:50 UTC, sepandhaghighi commented on pycm/pycm_obj.py
>          :type use_long_name: bool
:type shortener ...

2021-03-28 12:50 UTC, sepandhaghighi commented on pycm/pycm_output.py
> +    :param shortener: flag which shows if long names are used
:type shortener ...

2021-03-29 19:35 UTC, sepandhaghighi approved these changes
LGTM 💯 
@alirezazolanvari Please review this PR, if everything is okay, merge it after approval 🥇

2021-04-07 10:38 UTC, alirezazolanvari approved these changes
Nice work! LGTM

2021-04-08 08:30 UTC, merged