Coc update
sepandhaghighi/pycm pull request #425
Opened 2022-03-03 14:38 UTC by alirezazolanvari

#### Reference Issues/PRs
#399 
#### What does this implement/fix? Explain your changes.
Update the code of conduct according to the Contributor Covenant, version 2.1, available [here](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html).
#### Any other comments?

2022-03-03 18:22 UTC, sadrasabouri requested changes
Minor changes needed.

2022-03-03 18:22 UTC, sadrasabouri commented on .github/CODE_OF_CONDUCT.md
> +
Extra new line here.

2022-03-03 18:22 UTC, sadrasabouri commented on .github/CODE_OF_CONDUCT.md
> +  professional setting
Extra space here.

2022-03-04 07:43 UTC, sadrasabouri approved these changes

2022-03-04 10:01 UTC, sepandhaghighi requested changes
@alirezazolanvari Thanks for your efforts 💯 
Please update the changelog.
Something like :
`CODE_OF_CONDUCT.md` updated

2022-03-04 15:38 UTC, sepandhaghighi approved these changes
LGTM 💯

2022-03-04 15:38 UTC, merged