Compare
sepandhaghighi/pycm pull request #479
Opened 2023-01-23 23:05 UTC by alirezazolanvari

#### What does this implement/fix? Explain your changes.
Enhance the performance of `compare` by adding four more overall benchmarks and editing the default overall benchmarks' weights.  

#### Any other comments?
@sepandhaghighi Please modify `Document.ipynb` and `README.md` respectively.

#### References
[1]	 K. Villela, A. Silva, T. Vale, and E. S. de Almeida, "A survey on software variability management approaches," in _Proceedings of the 18th International Software Product Line Conference-Volume 1_, 2014, pp. 147-156. 
[2]	J. R. Saura, A. Reyes-Menendez, and P. Palos-Sanchez, "Are black Friday deals worth it? Mining Twitter users’ sentiment and behavior response," _Journal of Open Innovation: Technology, Market, and Complexity_, vol. 5, no. 3, p. 58, 2019.
[3]	P. Schubert and U. Leimstoll, "Importance and use of information technology in small and medium‐sized companies," _Electronic Markets_, vol. 17, no. 1, pp. 38-55, 2007.

2023-01-24 07:52 UTC, sadrasabouri requested changes
Minor changes needed.

2023-01-24 07:52 UTC, sadrasabouri commented on Test/compare_test.py
> +2     cm1    0.55              0.75238
What is this new alignments for?

2023-01-24 07:52 UTC, sadrasabouri commented on pycm/pycm_param.py
> +    "None": "None"}
I recommend the bellow format:
```python
    "None": "None",
}
```

2023-01-24 07:52 UTC, sadrasabouri commented on pycm/pycm_param.py
> +    "None": "None"}
```python
    "None": "None",
}
```

2023-01-24 07:52 UTC, sadrasabouri commented on pycm/pycm_param.py
> +    "None": "None"}
```python
    "None": "None",
}
```

2023-01-24 07:52 UTC, sadrasabouri commented on pycm/pycm_param.py
> +    "None": "None"}
```python
    "None": "None",
}
```

2023-01-24 07:52 UTC, sadrasabouri commented on pycm/pycm_param.py
> +    "SOA10": "SOA10(Pearson C)"}
```python
   "SOA10": "SOA10(Pearson C)",
}
```

2023-01-24 07:52 UTC, sadrasabouri commented on pycm/pycm_param.py
> +    "SOA10(Pearson C)": "Pearson's-C-interpretation"}
```python
    "SOA10(Pearson C)": "Pearson's-C-interpretation"}
}
```

2023-01-24 07:52 UTC, sadrasabouri commented on pycm/pycm_util.py
> +                                                   x[re.search(r'\d+', x).end():])])
We may need an `autopep8.sh` here. I also suggest the below snippet:
```python
sort_by = lambda x: [(x, False, False) if not re.findall(r'\d+', x) \
                else (x[:re.search(r'\d+', x).start()],
                      int(re.findall(r'\d+', x)[0]),
                      x[re.search(r'\d+', x).end():])])
return sorted(input_list, key=sort_by)
```

2023-01-25 19:28 UTC, sadrasabouri approved these changes

2023-01-26 14:38 UTC, sepandhaghighi approved these changes
LGTM 🚀

2023-01-26 14:39 UTC, sepandhaghighi commented
@sadrasabouri @alirezazolanvari Please re-review this PR 💯 
If everything is okay, **Squash/Merge** it after approval 🚀

2023-01-28 15:53 UTC, sadrasabouri approved these changes

2023-01-30 10:58 UTC, merged