Code style Update
sepandhaghighi/pycm pull request #486
Opened 2023-02-23 17:11 UTC by sadrasabouri

#### What does this implement/fix? Explain your changes.
This PR is a trial for enhancing the repositories' code style. Below is provided some overall changes:
+ Unifying code style in documentation, code, and tests
+ `__class_stat_init__` function in `pycm_handler.py` modified
+ `__overall_stat_init__` function in `pycm_handler.py`
+ `ConfusionMatrix.__init__` method
+ extra checks in `pycm_interpret.py`
+ `save_obj` modified

2023-02-23 22:30 UTC, sepandhaghighi requested changes

2023-02-23 22:30 UTC, sepandhaghighi commented on pycm/pycm_handler.py
> +def __imbalacement_handler__(cm, is_imbalanced):
imbalancement

2023-02-23 22:30 UTC, sepandhaghighi commented on CHANGELOG.md
> +- `__imbalacement_handler__` function
imbalancement

2023-02-23 22:30 UTC, sepandhaghighi commented on pycm/pycm_obj.py
> +from .pycm_handler import __imbalacement_handler__
imbalancement

2023-02-23 22:30 UTC, sepandhaghighi commented on pycm/pycm_handler.py
> +    for stat, field_name in OVERALL_PARAMS2FIELD_NAME.items():
I have a suggestion for this part:

1. We already have a `CLASS_PARAMS` in `pycm_params.py`, convert it to a dictionary that map `name` to `value` (they are the same at this moment)
2. Rename  `OVERALL_PARAMS2FIELD_NAME` to `OVERALL_PARAMS`
3. We need to update wherever these variables are used
4. We need to update `CONTRIBUTING.md`

2023-02-24 22:59 UTC, alirezazolanvari approved these changes
@sadrasabouri It's simply impressive. Thanks for your effort.

2023-02-28 21:57 UTC, sepandhaghighi approved these changes
LGTM 🚀

2023-02-28 21:57 UTC, merged