Doctests bug in `pytest` fixed
sepandhaghighi/pycm pull request #494
Opened 2023-04-16 17:06 UTC by sadrasabouri

#### Reference Issues/PRs
#488 

#### What does this implement/fix? Explain your changes.
In this PR below fixes are proposed:
+ Document tests modified so that the `pytest` run easily
+ Test system modified
+ Minor edit in `output_tests`

2023-04-17 07:22 UTC, alirezazolanvari approved these changes

2023-04-17 09:25 UTC, sepandhaghighi requested changes
My suggestions:

1. Remove `Test` argument from `pytest` calls
2. Update `pytest.ini` first line by `addopts = --doctest-modules --ignore=Otherfiles`

2023-04-17 09:25 UTC, sepandhaghighi commented on CHANGELOG.md
> +- Doctests modified
I would suggest you remove this line.

2023-04-19 00:57 UTC, sepandhaghighi approved these changes
LGTM 💯

2023-04-19 00:57 UTC, merged