Markdown Html Mixture
sepandhaghighi/pycm pull request #506
Opened 2023-05-09 13:02 UTC by sadrasabouri

#### Reference Issues/PRs
#496 
#### What does this implement/fix? Explain your changes.
Minor edits are applied after merging this PR:
+ `Document.ipynb`:
    - `$|C|$` in HTML snippets turned into `|C|`
    - `.` in HTML snippets turned into `<code>.</code>`
+ `Example4.ipynb`:
    - `$|C|$` in HTML snippets turned into `|C|`
    - `.` in HTML snippets turned into `<code>.</code>`

2023-05-09 13:22 UTC, sepandhaghighi requested changes
@sadrasabouri Thanks for your efforts 💯 

- `$|C|$` is a LateX formula so please revert this one.

- Some sections were missed, am I right?

![image](https://github.com/sepandhaghighi/pycm/assets/7515099/7a4a74b5-5ad6-4cd6-bafb-09668d47fe65)

2023-05-09 14:11 UTC, sadrasabouri commented
> @sadrasabouri Thanks for your efforts 100
> 
>     * `$|C|$` is a LateX formula so please revert this one.
> 
>     * Some sections were missed, am I right?
> 
> 
> ![image](https://user-images.githubusercontent.com/7515099/237106992-7a4a74b5-5ad6-4cd6-bafb-09668d47fe65.png)

You were right. I was using a mistaken regular expression for checking their existence. I updated it to the below code and now we hunted all of them:
```bash
sadra@beta:~/local/pycm$ grep "Notice" Document/Document.ipynb | grep "\`"
    "    <li><span style=\"color:red;\">Notice </span> : `matrix`, `normalized_matrix` & `normalized_table` added in <span style=\"color:red;\">version 1.5</span> (changed from print style)</li>\n",
    "    <li><span style=\"color:red;\">Notice </span> : `classes` added in <span style=\"color:red;\">version 3.2</span></li>\n",
```
They are fixed now and it's ready for your review.

2023-05-11 14:31 UTC, sepandhaghighi approved these changes
LGTM 🚀

2023-05-11 14:32 UTC, alirezazolanvari approved these changes

2023-05-11 14:32 UTC, merged