Refactoring
sepandhaghighi/pycm pull request #517
Opened 2023-08-18 07:45 UTC by tosemml

#### Reference Issues/PRs
This is a Refactoring

#### What does this implement/fix? Explain your changes.
This involves leveraging numpy operations for efficient computation of sums and dot products, enhancing the conciseness.

2023-08-18 13:55 UTC, sadrasabouri requested changes
Thank you for you PR.
Please take a look at my comments. Also check out [contribution guideline](https://github.com/sepandhaghighi/pycm/blob/master/.github/CONTRIBUTING.md), too.

You should update:
- `CHANGELOG.md`
- `AUTHORS.md`

2023-08-18 13:55 UTC, sadrasabouri commented on pycm/pycm_overall_func.py
> +        down = np.dot([TOP[i] for i in classes],[P[i] for i in classes])
Change it to:
```python
down = np.dot([TOP[i] for i in classes], [P[i] for i in classes])
```

2023-08-20 20:46 UTC, sadrasabouri requested changes
Thanks for your efforts. Please take a look at my comments.
Also change the PRs destination to `sepandhaghighi:dev` rather than `sepandhaghighi:master` (so as mentioned in `CONTRIBUTION.md`).

2023-08-20 20:46 UTC, sadrasabouri commented on AUTHORS.md
> +- Malinda Dilhara - University of Colorado Boulder ([Email](mailto:malinda.dilhara@gmail.com))
Remove this line, please.

2023-08-20 20:46 UTC, sadrasabouri commented on CHANGELOG.md
> +- Refactored pycm/pycm_overall_func.py to utilize NumPy methods.
Change it to:
```
### Changed
- `B_calc` function modified
```

2023-08-21 09:29 UTC, sepandhaghighi requested changes

2023-08-22 00:19 UTC, sadrasabouri commented on pycm/pycm_overall_func.py
> +        up = np.sum([TP[i]**2 for i in classes])
I think @sepandhaghighi is right here. Keeping the number of loops low is more important.

2023-08-24 14:54 UTC, alirezazolanvari commented
@tosemml Thanks for your efforts. I also think the refactored lines are inefficient. Especially for cases where the problem contains millions of class labels. For-loop overload cannot be compensated for by NumPy's efficiency in those cases. So, I'll close this PR, and if you have any other solutions for refactoring this part in an efficient way, please open a new PR.

BTW, it is so nice to see you've dived into the details of PyCM's source code. For sure there are many parts of the code that you can help us to improve in terms of both readability and efficiency.

2023-08-24 14:54 UTC, closed without merging