Issue templates
sepandhaghighi/pycm pull request #526
Opened 2023-11-16 07:21 UTC by sadrasabouri

#### Reference Issues/PRs
#522 

#### What does this implement/fix? Explain your changes.
### Added
- `feature_request.yaml` template
- `config.yml` for issue template
### Changed
- bug report template modified

2023-11-19 23:51 UTC, sepandhaghighi requested changes
@sadrasabouri Thanks for your efforts 💯 
Please take a look at my comments 🔥

2023-11-19 23:51 UTC, sepandhaghighi commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        - 4.0 (Default)
Is it necessary to write that `(Default)`?

2023-11-19 23:51 UTC, sepandhaghighi commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        - 3.12.0
I suggest `3.x` instead of `3.x.x`

2023-11-19 23:51 UTC, sepandhaghighi commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        - 3.11.0 (Default)
Is it necessary to write that `(Default)`?

2023-11-19 23:51 UTC, sepandhaghighi commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        - 4.0 (Default)
I believe that we should include a pattern in the `version_check.py` script.

2023-11-19 23:51 UTC, sepandhaghighi commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        - 4.0 (Default)
Please take a look at https://github.com/sepandhaghighi/pycm/releases.
We have 43 releases!

2023-11-19 23:51 UTC, sepandhaghighi commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +      required: false
I believe this field is required

2023-11-19 23:51 UTC, sepandhaghighi commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +      required: false
I believe this field is required

2023-11-19 23:51 UTC, sepandhaghighi commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +      required: false
I believe this field is required

2023-11-19 23:51 UTC, sepandhaghighi commented on CHANGELOG.md
> +- bug report template modified
- `Bug` instead of `bug`

2023-11-21 06:55 UTC, sadrasabouri commented
Changes applied @sepandhaghighi 
As you can see in the sandbox repository (for testing issue templates) the required field is not working.
I will work more on it to see what should I do and update this PR.

2023-11-23 22:27 UTC, sepandhaghighi requested changes
@sadrasabouri Thanks for your efforts 🔥 
Please take a look at my comments 💯 
Is it possible to unify all template file formats to either `.yaml` or .`yml` formats? Please update all files accordingly.

2023-11-23 22:27 UTC, sepandhaghighi commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +      label: Version
I believe that `PyCM version` is superior.

2023-11-23 22:27 UTC, sepandhaghighi commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Ask questions and discuss with other pycm community members
PyCM

2023-11-23 22:27 UTC, sepandhaghighi commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Ask questions and discuss with other pycm community members
PyCM

2023-11-23 22:27 UTC, sepandhaghighi commented on Otherfiles/RELEASE.md
Please update `#### Last Update:` section

2023-11-24 21:06 UTC, sepandhaghighi approved these changes
LGTM 🚀 
@alirezazolanvari Please review this PR 🔥

2023-12-02 12:42 UTC, sepandhaghighi commented
@alirezazolanvari Just a friendly reminder ⏲️

2023-12-06 09:42 UTC, alirezazolanvari commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        Thanks for taking the time to fill out this bug report!
My Suggestion:

" Thanks for your time to fill out this bug report!"

2023-12-06 09:43 UTC, alirezazolanvari commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: What you expected to happen?
What did you expect to happen?

2023-12-06 09:44 UTC, alirezazolanvari commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: What operating system are you using?
Which operating system are you using?

2023-12-06 09:46 UTC, alirezazolanvari requested changes
I left some comment about minor issues. Please check them out

2023-12-11 22:13 UTC, sepandhaghighi approved these changes

2023-12-11 22:14 UTC, sepandhaghighi commented
@alirezazolanvari Just a friendly reminder ⏲️

2023-12-14 10:47 UTC, merged