Messages unification
sepandhaghighi/pycm pull request #552
Opened 2024-08-13 11:22 UTC by alirezazolanvari

#### What does this implement/fix? Explain your changes.
Modify error and warning messages.

2024-08-13 16:49 UTC, sadrasabouri requested changes
Welcome back buddy. Thanks for your efforts. I left some comments.

2024-08-14 22:04 UTC, sepandhaghighi requested changes

2024-08-14 22:04 UTC, sepandhaghighi commented on pycm/pycm_param.py
> +COMPARE_CLASS_WEIGHT_ERROR = "class_weight must be a dictionary and specified for all classes."
I suggest using backticks (`` ` ``) around all parameter names. For example:

```
`class_weight`
```
or 
```
`class_benchmark_weight`
```

2024-08-15 12:10 UTC, alirezazolanvari commented on Test/error_test.py
> +pycm.pycm_error.pycmVectorError: This option is only available in vector mode.
@sepandhaghighi Do you have any idea about this?

2024-08-15 14:35 UTC, sepandhaghighi commented on Test/error_test.py
> +pycm.pycm_error.pycmVectorError: This option is only available in vector mode.
The error message type is correct because the position only has meaning in 'vector' mode.

2024-08-17 01:45 UTC, sadrasabouri approved these changes

2024-08-21 22:50 UTC, sepandhaghighi requested changes
@alirezazolanvari Thanks for your efforts 💯 
Please take a look at my comments 🔥

2024-08-21 22:50 UTC, sepandhaghighi commented on CHANGELOG.md
> +- Warning and error messages
Warning and error messages updated

2024-08-21 22:50 UTC, sepandhaghighi commented on Test/error_test.py
> +pycm.pycm_obj.pycmCompareError: Input must be an instance of pycm.ConfusionMatrix.
This error message is not accurate enough.
Input is a dictionary that consists of `pycm.ConfusionMatrix` objects not an instance of a `pycm.ConfusionMatrix`

2024-08-21 22:50 UTC, sepandhaghighi commented on Test/error_test.py
> +pycm.pycm_error.pycmAverageError: weight must be a dictionary and specified for all classes.
```
`weight`
```

2024-08-21 22:50 UTC, sepandhaghighi commented on Test/error_test.py
> +pycm.pycm_error.pycmAverageError: weight must be a dictionary and specified for all classes.
```
weight
```

2024-08-21 22:50 UTC, sepandhaghighi commented on pycm/pycm_param.py
> +THRESHOLDS_TYPE_ERROR = "Thresholds must be provided as a list or a NumPy array."
I think we can use 
```
`thresholds`
``` 
instead of `Thresholds` (Double check it)

2024-08-21 22:50 UTC, sepandhaghighi commented on pycm/pycm_param.py
> +THRESHOLDS_NUMERIC_ERROR = "Thresholds must contain only numeric values."
I think we can use 
```
`thresholds`
``` 
instead of `Thresholds` (Double check it)

2024-08-21 22:50 UTC, sepandhaghighi commented on pycm/pycm_param.py
> +CLASSES_TYPE_ERROR = "Classes must be provided as a list."
I think we can use 
```
`classes`
``` 
instead of `Classes` (Double check it)

2024-08-21 22:50 UTC, sepandhaghighi commented on pycm/pycm_param.py
> +AVERAGE_WEIGHT_ERROR = "weight must be a dictionary and specified for all classes."
I think we can use 
```
`weight`
``` 
instead of `weight` (Double check it)

2024-08-21 22:50 UTC, sepandhaghighi commented on pycm/pycm_param.py
> +DISTANCE_METRIC_TYPE_ERROR = "The metric type must be DistanceType."
I think we can use 
```
`metric`
``` 
instead of `The metric` (Double check it)

2024-09-06 07:53 UTC, sepandhaghighi commented
@alirezazolanvari Just a friendly reminder ⏲️

2024-09-09 11:11 UTC, sepandhaghighi requested changes
@alirezazolanvari Take a look at my comment 🔥

2024-09-09 11:11 UTC, sepandhaghighi commented on pycm/pycm_param.py
> +COMBINE_TYPE_ERROR = "Input must be a dictionary containing pycm.ConfusionMatrix objects."
Please double-check this.

2024-09-17 13:45 UTC, sepandhaghighi commented
@alirezazolanvari Just a friendly reminder ⌛

2024-09-18 15:45 UTC, sepandhaghighi approved these changes
LGTM 🚀

2024-09-18 15:47 UTC, sepandhaghighi commented
@sadrasabouri Please re-review 🔥 
If everything is okay, **Squash/Merge** it after approval 🚀

2024-09-19 05:57 UTC, sadrasabouri approved these changes
LGTM

2024-09-19 05:57 UTC, merged